const dt = require('../src/index')
const currentDate = new dt.D()
const date = new dt.D(2021, 4, 14, 15, 16, 17)
const date2 = new dt.D(currentDate.year+1, 5, 5, 6, 7, 8)
const date3 = new dt.D(currentDate._date.getFullYear(), currentDate._date.getMonth()+1)
const date4 = new dt.D(currentDate._date.getFullYear(), currentDate._date.getMonth(), currentDate._date.getDate()+1)
test('getters', () => {
    expect(date.year).toBe(2021)
    expect(date.yr).toBe(21)
    expect(date.month).toBe('April')
    expect(date.mon).toBe('Apr')
    expect(date.week).toBe('Wednesday')
    expect(date.wk).toBe('Wed')
    expect(date.date).toBe(14)
    expect(date2.dates).toBe('05')
    expect(date.hr).toBe(15)
    expect(date2.hours).toBe('06')
    expect(date.mins).toBe(16)
    expect(date2.minutes).toBe('07')
    expect(date.secs).toBe(17)
    expect(date2.seconds).toBe('08')
})
test('.format', () => {
    expect(date.format('m/d/Y H:I:S')).toBe('Apr/14/2021 15:16:17')
})
test('.when', () => {
    expect(date2.when()).toBe('1years')
    expect(date3.when()).toBe('1months')
    expect(date4.when()).toBe('1days')
})